image: gradle:6.8.3

pipelines:
  default:
    - parallel:
      - step:
          name: Build and Test
          caches:
            - gradle
          script:
            - gradle clean build --no-daemon
          after-script:
            - pipe: atlassian/checkstyle-report:0.2.0
      - step:
          name: Security Scan
          script:
            - pipe: atlassian/git-secrets-scan:0.4.3
  pull-requests:
    master:
      - step:
          name: Release
          caches:
            - gradle
          script:
            - git remote set-url origin $BITBUCKET_GIT_SSH_ORIGIN
            - gradle clean release --no-daemon
              -Prelease_commit_prefix="[gradle-release-plugin] prepare release"
              -Pdevelopment_commit_prefix="[gradle-release-plugin] prepare for next development iteration"
  tags:
    '**':
      - step:
          name: Publish mod jar
          caches:
            - gradle
          script:
            - gradle clean publish --no-daemon -Pscm_project_url=${BITBUCKET_GIT_HTTP_ORIGIN} -Pscm_connection_url=${BITBUCKET_GIT_SSH_ORIGIN}
              -Ppublish_maven_repo_username=${NEXUS_CI_USERNAME} -Ppublish_maven_repo_password=${NEXUS_CI_PASSWORD}